/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package coffeeshop;

import coffee.data.order_data;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author MyPC
 */
public class order_panel extends javax.swing.JPanel {

    /**
     * Creates new form order_panel
     */
    String[] headers = {"id_douong","soluong","dongia"};
    DefaultTableModel myModel;
    
    public order_panel() {
        initComponents();
        myModel = new DefaultTableModel(headers,0);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        txt_hoten = new javax.swing.JTextField();
        txt_diemtichluy = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txt_sodienthoai = new javax.swing.JTextField();
        btn_addkhachhang = new javax.swing.JButton();
        btn_check = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tb_chitietdonhang = new javax.swing.JTable();
        cb_douong = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        txt_madonhang = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txt_soluong = new javax.swing.JTextField();
        btn_adddouong = new javax.swing.JButton();
        btn_adddonhang = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        txt_tongtien = new javax.swing.JTextField();

        setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 51));
        jLabel1.setText("Order");

        jLabel2.setBackground(new java.awt.Color(102, 102, 102));
        jLabel2.setOpaque(true);

        jPanel1.setBackground(new java.awt.Color(250, 250, 250));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txt_hoten.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_hotenActionPerformed(evt);
            }
        });
        jPanel1.add(txt_hoten, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 60, 139, -1));

        txt_diemtichluy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_diemtichluyActionPerformed(evt);
            }
        });
        jPanel1.add(txt_diemtichluy, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 90, 139, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("Khách hàng");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 5, -1, -1));

        jLabel6.setText("Số điện thoại");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, -1, 20));

        jLabel7.setText("Tên khách hàng");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, -1, 20));

        jLabel8.setText("Điểm tích lũy");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, -1, -1));

        txt_sodienthoai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_sodienthoaiActionPerformed(evt);
            }
        });
        jPanel1.add(txt_sodienthoai, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 30, 139, -1));

        btn_addkhachhang.setBackground(new java.awt.Color(51, 0, 204));
        btn_addkhachhang.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btn_addkhachhang.setForeground(new java.awt.Color(255, 255, 255));
        btn_addkhachhang.setText("Add");
        btn_addkhachhang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_addkhachhangActionPerformed(evt);
            }
        });
        jPanel1.add(btn_addkhachhang, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 60, 70, -1));

        btn_check.setBackground(new java.awt.Color(0, 0, 0));
        btn_check.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btn_check.setForeground(new java.awt.Color(255, 255, 255));
        btn_check.setText("Check");
        btn_check.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_checkActionPerformed(evt);
            }
        });
        jPanel1.add(btn_check, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 30, 70, -1));

        jPanel2.setBackground(new java.awt.Color(250, 250, 250));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Danh sách order");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 5, -1, -1));

        tb_chitietdonhang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Tên đồ uống", "Số lượng", "Đơn giá"
            }
        ));
        jScrollPane1.setViewportView(tb_chitietdonhang);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 530, 150));

        cb_douong.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cà phê đen", "Cà phê nâu", "Cà phê cốt dừa", "Trà đào cam sả" }));
        jPanel2.add(cb_douong, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 60, 139, -1));

        jLabel4.setText("Số lượng");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, -1, 20));

        txt_madonhang.setEnabled(false);
        jPanel2.add(txt_madonhang, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 30, 80, -1));

        jLabel10.setText("Mã đơn hàng");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, -1, 20));

        jLabel11.setText("Chọn đồ uống");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, -1, 20));
        jPanel2.add(txt_soluong, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 90, 80, -1));

        btn_adddouong.setBackground(new java.awt.Color(255, 0, 0));
        btn_adddouong.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btn_adddouong.setForeground(new java.awt.Color(255, 255, 255));
        btn_adddouong.setText("+");
        btn_adddouong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_adddouongActionPerformed(evt);
            }
        });
        jPanel2.add(btn_adddouong, new org.netbeans.lib.awtextra.AbsoluteConstraints(185, 90, 54, -1));

        btn_adddonhang.setBackground(new java.awt.Color(0, 153, 51));
        btn_adddonhang.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btn_adddonhang.setForeground(new java.awt.Color(255, 255, 255));
        btn_adddonhang.setText("New");
        btn_adddonhang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_adddonhangActionPerformed(evt);
            }
        });
        jPanel2.add(btn_adddonhang, new org.netbeans.lib.awtextra.AbsoluteConstraints(185, 30, 55, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 0, 0));
        jLabel9.setText("Tổng tiền");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 90, -1, 20));
        jPanel2.add(txt_tongtien, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 90, 80, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 549, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 549, Short.MAX_VALUE))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 276, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txt_sodienthoaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_sodienthoaiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_sodienthoaiActionPerformed

    private void txt_hotenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_hotenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_hotenActionPerformed

    private void txt_diemtichluyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_diemtichluyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_diemtichluyActionPerformed

    private void btn_adddonhangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_adddonhangActionPerformed
        // TODO add your handling code here:
        order_data ord_data=new order_data();
        ord_data.addDonhang("", "", "", "", "");
        String text=ord_data.getIdDonhang();
        System.out.println(text);
        txt_madonhang.setText(text);
    }//GEN-LAST:event_btn_adddonhangActionPerformed

    private void btn_addkhachhangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_addkhachhangActionPerformed
        // TODO add your handling code here:
        order_data ord_data=new order_data();
        ord_data.addKhachhang(txt_sodienthoai.getText(), txt_hoten.getText());
    }//GEN-LAST:event_btn_addkhachhangActionPerformed

    private void btn_checkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_checkActionPerformed
        // TODO add your handling code here:
        order_data ord_data=new order_data();
        String[] data=new String[3];
        int check = ord_data.checkKhachhang(txt_sodienthoai.getText());
        System.out.println(check);
        if(check==1){
            data=ord_data.getKhachhang(txt_sodienthoai.getText());
            txt_hoten.setText(data[0]);
            txt_diemtichluy.setText(data[2]);
        }
    }//GEN-LAST:event_btn_checkActionPerformed

    private void btn_adddouongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_adddouongActionPerformed
        // TODO add your handling code here:
        order_data ord_data = new order_data();
        String[] datadouong= new String[3];
        datadouong = ord_data.getDouong(cb_douong.getSelectedItem().toString());
        //add do uong vao chi tiet don hang
        ord_data.addDouong(txt_madonhang.getText(), datadouong[0], txt_soluong.getText(), datadouong[2]);
        //Load chi tiet don hang len bang
        ord_data.GetChitietdoihang(myModel, txt_madonhang.getText());
        tb_chitietdonhang.setModel(myModel);
        int tongtien=ord_data.getTongtien(txt_madonhang.getText());
        txt_tongtien.setText(Integer.toString(tongtien));
    }//GEN-LAST:event_btn_adddouongActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_adddonhang;
    private javax.swing.JButton btn_adddouong;
    private javax.swing.JButton btn_addkhachhang;
    private javax.swing.JButton btn_check;
    private javax.swing.JComboBox<String> cb_douong;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tb_chitietdonhang;
    private javax.swing.JTextField txt_diemtichluy;
    private javax.swing.JTextField txt_hoten;
    private javax.swing.JTextField txt_madonhang;
    private javax.swing.JTextField txt_sodienthoai;
    private javax.swing.JTextField txt_soluong;
    private javax.swing.JTextField txt_tongtien;
    // End of variables declaration//GEN-END:variables
}
